### ISSUE TITLE
TypeError: object of type 'function' has no len()

### ISSUE THREAD

**Issue by drewbthomas** [SaberD/annotated-images#5]
I keep getting this error when running annotated_images.split. Any ideas?

**Comment by SaberD** [comment]
I could not recreate your issue.

I have added a test jupyter note that downloads a test dataset and runs the commands on it: [test.ipynb](https://github.com/SaberD/annotated-images/blob/master/test.ipynb)

**Comment by SaberD** [comment]
I got the same error now when I'm trying to split a **classification** dataset organized like this /dataset/class1 /dataset/class2.
